baseURL: "https://tools.scientific-python.org/"
title: "Scientific Python Tools"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Tools for scientific Python developers and packages."
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Scientific Python Tools
    link: /
  navbarlogoshow: true
  navbar:
    - title: Home
      url: https://scientific-python.org/
    - title: Blog
      url: https://blog.scientific-python.org
    - title: Learn
      url: https://learn.scientific-python.org
    - title: Tools
      url: /
  panel:
    tiles:
      - buttonText: Web Theme
        url: https://theme.scientific-python.org
        text: ...
      - buttonText: Python Packages
        url: /
        text: ...
      - buttonText: Github Actions
        url: /
        text: ...
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://scientific-python.org
        icon: scientific-python
      - link: https://github.com/scientific-python/learn.scientific-python.org
        icon: github
      - link: https://www.youtube.com/c/ScientificPython-org
        icon: youtube
      - link: https://twitter.com/scientific_py
        icon: twitter
      - link: https://facebook.com/scientific.python
        icon: facebook
      - link: https://www.instagram.com/scientific.python/
        icon: instagram
      - link: https://www.tiktok.com/@scientific.python
        icon: tiktok
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord
      - link: https://blog.scientific-python.org/atom.xml
        icon: rss-feed
      - link: https://discuss.scientific-python.org
        icon: discourse
    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
      column2:
        links:
      column3:
        links:
