[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/2365790?v=4"'
alt = 'Avatar of Eric Larson'
{{< /image >}}
Eric Larson'''
link = 'https://github.com/larsoner'
